name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dbt
      run: pip install dbt-postgres

    - name: Set up dbt profile
      run: |
        mkdir -p ~/.dbt
        echo "
        datawarehouse:
          target: prod
          outputs:
            prod:
              type: postgres
              host: ${{ secrets.DB_HOST_PROD }}
              port: ${{ secrets.DB_PORT_PROD }}
              user: ${{ secrets.DB_USER_PROD }}
              password: ${{ secrets.DB_PASS_PROD }}
              dbname: ${{ secrets.DB_NAME_PROD }}
              schema: ${{ secrets.DB_SCHEMA_PROD }}
              threads: ${{ secrets.DB_THREADS_PROD }}
        " > ~/.dbt/profiles.yml

    - name: Install dependencies and generate docs
      run: |
        cd datawarehouse
        dbt docs generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./datawarehouse/target